{% set name = "gsmap" %}
{% set version = "1.65" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/gsMap/{{ name }}-{{ version }}.tar.gz"
  sha256: 0af3d1eeb61b3545e8b58ff43f8a44e8e5f4987bb2f2029c1bbdbbf11aebf45e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv  # Using pip to install from source

requirements:
  host:
    - python >=3.8
    - pip
    - flit >=3.2,<4

  run:
    - python >=3.8
    - numpy
    - pandas
    - scipy
    - scikit-learn
    - matplotlib
    - seaborn
    - tqdm
    - progress
    - pyyaml
    - pytorch
    - pytorch_geometric
    - pyranges
    - pyfiglet
    - plotly
    - kaleido-core
    - jinja2
    - scanpy
    - zarr
    - bitarray
    - pyarrow
    - scikit-misc

test:
  imports:
    - gsMap
  commands:
    - gsmap --help

about:
  home: https://github.com/LeonSong1995/gsMap
  license: MIT
  license_file: LICENSE
  summary: "gsMap (genetically informed spatial mapping of cells for complex traits)"
  description: |
    gsMap integrates spatial transcriptomics (ST) data with genome-wide association study (GWAS) summary statistics to map cells to human complex traits, including diseases, in a spatially resolved manner.
  authors:
    - name: liyang
      email: songliyang@westlake.edu.cn
    - name: wenhao
      email: chenwenhao@westlake.edu.cn
  doc_url: "https://yanglab.westlake.edu.cn/gsmap/document"
  dev_url: "https://github.com/LeonSong1995/gsMap"

extra:
  recipe-maintainers:
    - Ganten-Hornby
    - leonSong1995
